name: sorabbyngo_mobile
description: Sorabbyngo CHW mobile app — offline-first
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  provider: ^6.1.0
  connectivity_plus: ^5.0.0
  geolocator: ^10.1.0

flutter:
  uses-material-design: true
